import IOTATransaction

From = 'HGW9HB9LJPYUGVHNGCPLFKKPNZAIIFHZBDHKSGMQKFMANUBASSMSV9TAJSSMPRZZU9SFZULXKJ9YLAIUA'
To = 'BXOM9LUNLPSEXBRJV9UUNLHSUHABEOGHQOGNBNBUEYSGOFZOEPYKEYRSFTXBOEJLUODUQXXGQ9NWQBSGH'


a = IOTATransaction.IOTATransaction(From)
Ftag = 'IPTABLETEST'
fhash = a.GetFhash('accounting')

pt = a.MakePreparingTransaction(To, fhash, tag=Ftag)
a.SendTransaction([pt])
print(a.GetTransactionHash())

#print(a.GetTransactionMessage('WGRXJ9USIJ9MXFTGBYTRHH9BPKBAAP9ZJIKHYRRFVSWFXCJHCIKVCZMBQ9QRGFRZRTIMRIZUWNGYZ9999'))

